on:
  push:
    paths:
      - 'onstage_entry_rules.adoc'
      - 'preamble.tex'
      - 'specific_preamble_onstage_entry_rules.tex'

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: build the rules
        run: |
          docker run -v $(pwd):/documents asciidoctor/docker-asciidoctor .ci/adoc-to-tex.sh onstage_entry_rules
          docker run -v $(pwd):/documents mrshu/texlive-dblatex .ci/tex-to-pdf.sh onstage_entry_rules
          mkdir -p dist/${GITHUB_REF#refs/heads/}/
          cp -R ./media rules_documents/* dist/${GITHUB_REF#refs/heads/}/

      - name: publish the rules
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./dist
          keep_files: True
